# Generated by Django 6.0.5 on 2026-05-31 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='academic_users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, null=True)),
                ('password', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'academic_users',
            },
        ),
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('e_mec', models.CharField(max_length=255)),
                ('max_length', models.IntegerField()),
            ],
            options={
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='institution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('acronym', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'institution',
            },
        ),
        migrations.CreateModel(
            name='permissions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('nickname', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'permissions',
            },
        ),
        migrations.CreateModel(
            name='classes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('max_students', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('open', models.IntegerField()),
                ('fk_professor', models.ForeignKey(db_column='fk_professor', on_delete=django.db.models.deletion.CASCADE, to='matscholar_app.academic_users')),
            ],
            options={
                'db_table': 'classes',
            },
        ),
        migrations.CreateModel(
            name='classes_courses',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('id_class', models.ForeignKey(db_column='id_class', on_delete=django.db.models.deletion.CASCADE, to='matscholar_app.classes')),
                ('id_course', models.ForeignKey(db_column='id_course', on_delete=django.db.models.deletion.CASCADE, to='matscholar_app.courses')),
            ],
            options={
                'db_table': 'classes_courses',
            },
        ),
        migrations.AddField(
            model_name='academic_users',
            name='fk_institution',
            field=models.ForeignKey(db_column='fk_institution', on_delete=django.db.models.deletion.CASCADE, to='matscholar_app.institution'),
        ),
        migrations.CreateModel(
            name='academic_users_permissions',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to='matscholar_app.academic_users')),
                ('id_nickname', models.ForeignKey(db_column='id_nickname', on_delete=django.db.models.deletion.CASCADE, to='matscholar_app.permissions')),
            ],
            options={
                'db_table': 'academic_users_permissions',
            },
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('RA', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('year_of_entry', models.IntegerField()),
                ('fk_course', models.ForeignKey(db_column='fk_course', on_delete=django.db.models.deletion.CASCADE, to='matscholar_app.courses')),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='final_grades',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('final_grade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_class', models.ForeignKey(db_column='id_class', on_delete=django.db.models.deletion.CASCADE, to='matscholar_app.classes')),
                ('id_student', models.ForeignKey(db_column='id_student', on_delete=django.db.models.deletion.CASCADE, to='matscholar_app.students')),
            ],
            options={
                'db_table': 'final_grades',
            },
        ),
        migrations.CreateModel(
            name='assignments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('grade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fk_class', models.ForeignKey(db_column='fk_class', on_delete=django.db.models.deletion.CASCADE, to='matscholar_app.classes')),
                ('fk_id_student', models.ForeignKey(db_column='fk_id_student', on_delete=django.db.models.deletion.CASCADE, to='matscholar_app.students')),
            ],
            options={
                'db_table': 'assignments',
            },
        ),
        migrations.CreateModel(
            name='students_classes_actual',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('id_class', models.ForeignKey(db_column='id_class', on_delete=django.db.models.deletion.CASCADE, to='matscholar_app.classes')),
                ('id_student', models.ForeignKey(db_column='id_student', on_delete=django.db.models.deletion.CASCADE, to='matscholar_app.students')),
            ],
            options={
                'db_table': 'students_classes_actual',
            },
        ),
        migrations.CreateModel(
            name='students_classes_missing',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('id_class', models.ForeignKey(db_column='id_class', on_delete=django.db.models.deletion.CASCADE, to='matscholar_app.classes')),
                ('id_student', models.ForeignKey(db_column='id_student', on_delete=django.db.models.deletion.CASCADE, to='matscholar_app.students')),
            ],
            options={
                'db_table': 'students_classes_missing',
            },
        ),
    ]
