# Generated by Django 6.0.5 on 2026-06-01 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matscholar_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='fk_institution',
            field=models.ForeignKey(db_column='fk_institution', null=True, on_delete=django.db.models.deletion.CASCADE, to='matscholar_app.institution'),
        ),
    ]
