# Generated by Django 6.0.5 on 2026-06-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matscholar_app', '0002_courses_fk_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='password',
            field=models.CharField(default='e', max_length=255),
            preserve_default=False,
        ),
    ]
