# Generated by Django 6.0.5 on 2026-06-15 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matscholar_app', '0003_students_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='fk_institution',
            field=models.ForeignKey(db_column='fk_institution', null=True, on_delete=django.db.models.deletion.CASCADE, to='matscholar_app.institution'),
        ),
    ]
