# Generated by Django 6.0.5 on 2026-06-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matscholar_app', '0004_students_fk_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='initial',
            field=models.IntegerField(default=1),
        ),
    ]
