# Generated by Django 6.0.5 on 2026-06-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matscholar_app', '0005_classes_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='abstract',
            field=models.IntegerField(default=0),
        ),
    ]
