# Generated by Django 6.0.5 on 2026-06-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matscholar_app', '0006_classes_abstract'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='acronym',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
