# Generated by Django 6.0.5 on 2026-06-16 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matscholar_app', '0007_courses_acronym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='fk_professor',
            field=models.ForeignKey(db_column='fk_professor', null=True, on_delete=django.db.models.deletion.CASCADE, to='matscholar_app.academic_users'),
        ),
    ]
