# Generated by Django 6.0.5 on 2026-06-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matscholar_app', '0008_alter_classes_fk_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='classes',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
