# Generated by Django 6.0.5 on 2026-06-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matscholar_app', '0009_alter_classes_end_date_alter_classes_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='max_students',
            field=models.IntegerField(null=True),
        ),
    ]
