# Generated by Django 6.0.5 on 2026-06-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matscholar_app', '0010_alter_classes_max_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='graduated',
            field=models.IntegerField(default=0),
        ),
    ]
