# Generated by Django 6.0.5 on 2026-07-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matscholar_app', '0011_students_graduated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='grade',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
