# Generated by Django 6.0.5 on 2026-07-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matscholar_app', '0012_alter_assignments_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='deadline',
            field=models.DateField(null=True),
        ),
    ]
