# Generated by Django 6.0.5 on 2026-07-09 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matscholar_app', '0013_assignments_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignments',
            name='fk_id_student',
        ),
    ]
