# Generated by Django 6.0.5 on 2026-07-09 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matscholar_app', '0014_remove_assignments_fk_id_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignments',
            name='grade',
        ),
        migrations.CreateModel(
            name='assignments_students',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('grade', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('fk_id_class', models.ForeignKey(db_column='id_class', on_delete=django.db.models.deletion.CASCADE, to='matscholar_app.classes')),
                ('fk_id_student', models.ForeignKey(db_column='id_student', on_delete=django.db.models.deletion.CASCADE, to='matscholar_app.students')),
            ],
        ),
    ]
