# Generated by Django 6.0.5 on 2026-07-10 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matscholar_app', '0015_remove_assignments_grade_assignments_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignments_students',
            name='fk_id_class',
        ),
        migrations.AddField(
            model_name='assignments',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='assignments_students',
            name='feedback',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='assignments_students',
            name='fk_id_assignment',
            field=models.ForeignKey(db_column='fk_assignment', default=-1, on_delete=django.db.models.deletion.CASCADE, to='matscholar_app.assignments'),
        ),
        migrations.AlterField(
            model_name='assignments_students',
            name='fk_id_student',
            field=models.ForeignKey(db_column='fk_student', on_delete=django.db.models.deletion.CASCADE, to='matscholar_app.students'),
        ),
        migrations.AlterModelTable(
            name='assignments_students',
            table='assignments_students',
        ),
    ]
