# Generated by Django 6.0.5 on 2026-07-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matscholar_app', '0016_remove_assignments_students_fk_id_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='max_grade',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='assignments',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
