# Generated by Django 6.0.5 on 2026-07-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matscholar_app', '0017_assignments_max_grade_assignments_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='students_classes_actual',
            name='absence',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='students_classes_actual',
            name='attendence',
            field=models.IntegerField(null=True),
        ),
    ]
