# Generated by Django 6.0.5 on 2026-07-14 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matscholar_app', '0018_students_classes_actual_absence_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students_classes_actual',
            old_name='attendence',
            new_name='attendance',
        ),
    ]
