# Generated by Django 6.0.5 on 2026-07-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matscholar_app', '0019_rename_attendence_students_classes_actual_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='universal_absence_limit',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='assignments_students',
            name='grade',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='final_grades',
            name='final_grade',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
