# Generated by Django 6.0.5 on 2026-07-14 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matscholar_app', '0020_institution_universal_absence_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='final_grades',
            name='final_attendance',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
